### ISSUE TITLE
I have an error.

### ISSUE THREAD

**Issue by thedrewen** [CustomiesDevs/Customies#112]
CustomiesBlockFactory::getInstance()->registerBlock(static fn(int $id) => new Block(new BlockIdentifier($id, 0), "Example Block", new BlockBreakInfo(1)), "customies:example_block");

Error : [19:09:25.953] (B[Server thread/CRITICAL]: (BArgumentCountError: "Too few arguments to function TheDreWen\NeoPlugin\Main::TheDreWen\NeoPlugin\{closure}(), 0 passed in phar:///var/lib/pufferpanel/servers/a42e1521/plugins/Customies.phar/src/block/CustomiesBlockFactory.php on line 83 and exactly 1 expected" (EXCEPTION) in "plugins/NeoPlugin/src/Main" at line 25
--- Stack trace ---
  #0 plugins/Customies.phar/src/block/CustomiesBlockFactory(83): TheDreWen\NeoPlugin\Main::TheDreWen\NeoPlugin\{closure}()
  #1 plugins/NeoPlugin/src/Main(27): customiesdevs\customies\block\CustomiesBlockFactory->registerBlock(object Closure#112232, string[23] customies:example_block)
  #2 pmsrc/src/plugin/PluginBase(119): TheDreWen\NeoPlugin\Main->onEnable()
  #3 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #4 pmsrc/src/Server(1390): pocketmine\plugin\PluginManager->enablePlugin(object TheDreWen\NeoPlugin\Main#168746)
  #5 pmsrc/src/Server(1034): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41678)
  #6 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[38] /var/lib/pufferpanel/servers/a42e1521/, string[46] /var/lib/pufferpanel/servers/a42e1521/plugins/)
  #7 pmsrc/src/PocketMine(357): pocketmine\server()
  #8 pmsrc(11): require(string[82] phar:///var/lib/pufferpanel/servers/a42e1521/PocketMine-MP.phar/src/PocketMine.p)
--- End of exception information ---(B(B
[19:09:25.953] (B[Server thread/EMERGENCY]: (BAn unrecoverable error has occurred and the server has crashed. Creating a crash dump(B(B
[19:09:25.957] (B[Server thread/EMERGENCY]: (BPlease upload the "/var/lib/pufferpanel/servers/a42e1521/crashdumps/Thu_Oct_26-19.09.25-UTC_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.(B(B
]0;[19:09:25.957] (B[Server thread/EMERGENCY]: (BForcing server shutdown(B(B

**Comment by DemonicDev** [comment]
got the same error while updating from api 4 to api 5 lol

**Comment by DemonicDev** [comment]
use 1.3.4 that should fix it
