### ISSUE TITLE
1.20.60 broke something

### ISSUE THREAD

**Issue by dadodasyra** [CustomiesDevs/Customies#119]
The list of custom blocks seems broken as the shown blocks to the player are not the right ones (stairs instead of air)

**Comment by AzOxStOz** [comment]
but for the item texture i don't know

**Comment by AzOxStOz** [comment]
maybe something change in the vanilla pack

**Comment by TwistedAsylumMC** [comment]
https://github.com/CustomiesDevs/Customies/commit/87ee6060517e63f92bc2f500dd9086377c2e6d60
