### ISSUE TITLE
Creative Inventory

### ISSUE THREAD

**Issue by SquashOnGithub** [CustomiesDevs/Customies#12]
Please regsiter block and item on the creative inventory

**Comment by Steellgold** [comment]
Hey! https://github.com/CustomiesDevs/Customies/pull/13

**Comment by Steellgold** [comment]
items and blocks can be sort in my [Pull Request](https://github.com/CustomiesDevs/Customies/pull/13)

**Comment by Steellgold** [comment]
Is only in a pull request, you will be notified when this happens in the master branch
