### ISSUE TITLE
Null ☠️

### ISSUE THREAD

**Issue by GabBiswajit** [CustomiesDevs/Customies#121]
While attempting to register an emerald chestplate item using the `CustomiesItemFactory` class, the following code snippet is used:

```php
register = CustomiesItemFactory::getInstance()->registerItem(Emerald_Chestplate::class, "armorsapi:emerald_chestplate", "emerald_chestplate");
```

Subsequently, an attempt is made to parse the string `"emerald_chestplate"` into an item using the `StringToItemParser` class. However, this operation is returning `null`.

Please address this issue. Thank you! 🥲

**Comment by ShadowMikado** [comment]
HI, you can use `StringToItemParser::getInstance()->registerAlias()`

**Comment by ShadowMikado** [comment]
```php
public function registerAlias(string $existing, string $alias) : void{
```
https://github.com/pmmp/PocketMine-MP/blob/50e2c469a547a16a23b2dc691e70a51d34e29395/src/utils/StringToTParser.php#L64
