### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by JustTimmm** [CustomiesDevs/Customies#127]
Hey, do you know why my textures don't want to be put on? It does it to me and to several of my friends:

```php
$this->initComponent("diamond_hoe", $creative);
```

**Comment by and7ey** [comment]
@JustTimmm have you found any solution? Textures are also not displayed in my case.

**Comment by Atara6431** [comment]
So have you all solved it? I also have this problem

**Comment by and7ey** [comment]
> So have you all solved it? I also have this problem

@Atara6431 I've downloaded the latest version of the plugin from github, looks like the poggit contains the old version

**Comment by Atara6431** [comment]
@and7ey which one?last updated five months ago on github?

**Comment by and7ey** [comment]
@Atara6431 yes

**Comment by floriiian** [comment]
My custom item hotbar textures aren't working either!

**Comment by Pedhot-Dev** [comment]
> My custom item textures aren't working either, the icon is always empty!

same bro

**Comment by floriiian** [comment]
> > My custom item textures aren't working either, the icon is always empty!
> 
> same bro

Check out my pull request, you'll have to edit Customies tho.

**Comment by TwistedAsylumMC** [comment]
This is fixed
