### ISSUE TITLE
Shadow Bug?

### ISSUE THREAD

**Issue by lenlenlL6** [CustomiesDevs/Customies#134]
Something happened to my plugin, it looked like something was blocking the light.
![Screenshot_20240629-204509_Minecraft](https://github.com/CustomiesDevs/Customies/assets/62021442/51d318d6-2374-427e-a5b2-83be49ac45d9)
![Screenshot_20240629-221723_Minecraft](https://github.com/CustomiesDevs/Customies/assets/62021442/130ce781-219a-45f2-b22f-9fa4c5a6209a)
![Screenshot_20240629-221741_Minecraft](https://github.com/CustomiesDevs/Customies/assets/62021442/f1943ba9-2a08-45ba-8cf6-3159c5865fb7)

**Comment by TwistedAsylumMC** [comment]
If it isn't a full cube then extend Transparent from pocketmine

**Comment by lenlenlL6** [comment]
Thanks it worked.
