### ISSUE TITLE
Item icons do not appear in the game!

### ISSUE THREAD

**Issue by ClickedTran** [CustomiesDevs/Customies#137]
Hello developers, today I wrote this issue to ask why my plugin doesn't show the item icon even though it has been registered?

IMAGE: 
![received_439576105585976](https://github.com/CustomiesDevs/Customies/assets/58399779/4024cf0f-2a3a-42a8-a34d-7d6ede469b52)
![received_3904784456411080](https://github.com/CustomiesDevs/Customies/assets/58399779/5360f6a7-be4f-4da5-b946-c6fcc74f0538)
![received_480194321324656](https://github.com/CustomiesDevs/Customies/assets/58399779/9f9bf199-c231-4162-9c9e-ec18278b189a)
![received_469371952392149](https://github.com/CustomiesDevs/Customies/assets/58399779/ab6b49b9-0a8a-41c2-83d3-b3bfcda92dee)
![received_419286307776028](https://github.com/CustomiesDevs/Customies/assets/58399779/ae298c45-48e5-4423-b282-21042a62ccc8)

Please help me :((

**Comment by BobaTeaman** [comment]
you could try and update the pack uuid I had a issue kinda like this and I just had to change it

**Comment by ClickedTran** [comment]
> bạn có thể thử và cập nhật gói uuid Tôi đã gặp một vấn đề tương tự như thế này và tôi chỉ cần thay đổi nó

I get the latest uuid from the uuidgenerator, so there's no chance of the uuid getting old

**Comment by ShadowMikado** [comment]
It's a Customies bug
use this fork [Customies NG](https://github.com/DavyCraft648/Customies-NG)
