### ISSUE TITLE
Error getting unknown item

### ISSUE THREAD

**Issue by valentin-tetushkin** [CustomiesDevs/Customies#14]
An error occurs when trying to get unknown item from CustomiesItemFactory. Can you add «isRegistered» method?

**Comment by valentin-tetushkin** [comment]
ErrorException: "Undefined array key "test"" (EXCEPTION) in "plugins/Customies/src/item/CustomiesItemFactory" at line 37

**Comment by ScarceityPvP** [comment]
Can you please elaborate, this looks to be an error that shouldn't be possible. A null operator is used when the itemTableEntries property is indexed so this shouldn't really be possible. 

```php
		$id = $this->itemTableEntries[$identifier]?->getNumericId();
```

**Comment by valentin-tetushkin** [comment]
But null operator prevents error of undefined method, not error of undefined array key

**Comment by valentin-tetushkin** [comment]
```
$id = ($this->itemTableEntries[$identifier] ?? null)?->getNumericId();
```

This should work right

**Comment by ScarceityPvP** [comment]
I believe so, can you test it out and PR?
