### ISSUE TITLE
texture cannot be displayed

### ISSUE THREAD

**Issue by Atara6431** [CustomiesDevs/Customies#21]
I create a new sword successfully,but the texture cannot be displayed,I put a png in texture/items/sword1.
I also try to only change your test items texture_path
food_items:
  example_food_item:
    name: test_food # Always use "_" for spaces.
    id: 1001 # required
    meta: 0 # optional | default is 0
    is_potion: false # if true, The animation of eating will be like a potion. | optional default is false
    texture_path: newapple # required
    max_stack_size: 32 # optional | default is 64
    can_always_eat: true # This allows you to always eat the item even if the player is not hungry | optional default is false
    food_restore: 4 # use only integer numbers for this value. | required
    saturation_restore: 15.0 # use only float numbers for this value. | required
it still can't load the texture in texture/items/newapple
besides，some types like your armor_items can't be loaded，
armor_items:
  example_helmet:
    name: feather
    id: 1003
    meta: 0
    type: helmet # helmet | chestplate | leggings | boots - required
    texture_path: iron_helmet
    defense_points: 5 # required
    durability: 500 # required
This is your preset. I haven't made any changes，but in the game ， the texture of this also can't be displayed
![image](https://user-images.githubusercontent.com/48610466/175807344-b735dc7f-5f7c-4ea7-af73-f8af80a6bb33.png)

**Comment by TwistedAsylumMC** [comment]
I'm not sure what you mean, this is clearly not our plugin because we don't have a config file like the one you mentioned
