### ISSUE TITLE
Support PM5 (modern-world-support)

### ISSUE THREAD

**Issue by pooooooon** [CustomiesDevs/Customies#24]
PM5 [modern-world-support](https://github.com/pmmp/PocketMine-MP/tree/modern-world-support) was breaking a lot of blocks , items , chunk and it was use in this plugin
blockMapping and itemMapping was changed alot

**Comment by Unickorn** [comment]
PM5 is still rather bleeding-edge, we are currently not planning on supporting it just yet.
