### ISSUE TITLE
Resolve Bug Size Items 

### ISSUE THREAD

**Issue by RemBog** [CustomiesDevs/Customies#28]
Hello, could you add the possibility of having items in 64x64 and 32x32 in addition to 16x16 please? 
I know it is possible thanks to nbt.

**Comment by abimek** [comment]
Do we even specify a 16x16 limitation. From what I believe you can provide a texture file of any of those sizes and the client will render them accordingly.

**Comment by RemBog** [comment]
Yes but by adding nbt there is a way to solve this problem.
 The CustomItemLoader plugin does that.

**Comment by TwistedAsylumMC** [comment]
This is resolved in https://github.com/CustomiesDevs/Customies/commit/47dedd4e907d45163b30de050ab3111167a0fd66, but it will be in a release which has other API breaking changes. I will close this issue after the release has been created

**Comment by TwistedAsylumMC** [comment]
Version 1.1.0 has been submitted to poggit and an update guide can be found [on the wiki](https://github.com/CustomiesDevs/Customies/wiki/Custom-Blocks#updating-from-v107---v110). To fix the issue you are having, you can follow [this guide](https://github.com/CustomiesDevs/Customies/wiki/Custom-Items#regulating-held-item-scale) from the wiki.
