### ISSUE TITLE
Items static register

### ISSUE THREAD

**Issue by Gewinum** [CustomiesDevs/Customies#30]
When there are multiple plugins using Customies, problems appear. It is necessary to make them depend on each other, so they load in certain order.

Imagine, we have plugins for copper and donate cases.

On first server load, copper was first loaded and donate cases after. I got copper and restarted the server. On next server startup donate cases loaded first, so instead of copper I got some OP donate case.

Thats because Customies dynamically assigns id to each item. Maybe its possible to make config, in which we can manage the item ids? It would be better.

**Comment by Unickorn** [comment]
Sounds like #34 could be a fix to this.
