### ISSUE TITLE
add CustomiesAPI::getInstance()->start()

### ISSUE THREAD

**Issue by ShadowMikado** [CustomiesDevs/Customies#36]
Can you add a way to start the api without having the plugin Customies in the Plugins folder. 

And can you explain explicitly how can we create custom blocks (because you don't really explain in the wiki)
<img width="300" alt="Screenshot(1)" src="https://user-images.githubusercontent.com/89030950/192060841-5d6f83ee-8d31-4df5-a330-f1ef716c4f47.png">

<img width="300" alt="Screenshot(2)" src="https://user-images.githubusercontent.com/89030950/192061765-07b918b7-ffee-49f3-83ef-28967d4c383b.png">

**Comment by TwistedAsylumMC** [comment]
> Can you add a way to start the api without having the plugin Customies in the Plugins folder.
What exactly do you mean by this? Customies cannot be used as a virion or composer library due to the nature of how it works in terms of the block palette. There must only be one runtime of Customise per server, making it impossible to use as anything other than a plugin.

> And can you explain explicitly how can we create custom blocks (because you don't really explain in the wiki)
The wiki is only intended to describe how to use the plugin, if you want to learn how to do the resource pack side of things you can use other sources of documentation such as [bedrock.dev](https://bedrock.dev)

**Comment by ShadowMikado** [comment]
Ok thx

**Comment by ShadowMikado** [comment]
But I would just know exactly what I should put in the class of my custom block

**Comment by TwistedAsylumMC** [comment]
You are not required to put anything in the class, you can use any of the built in classes from PMMP

**Comment by ShadowMikado** [comment]
And how can I put my custom texture and register the block in the creative inventory (without using custom models and material) if it's possible

**Comment by ShadowMikado** [comment]
And I wan't to create a custom id for my block, how can i do this ?

**Comment by ShadowMikado** [comment]
@TwistedAsylumMC

**Comment by TwistedAsylumMC** [comment]
> And how can I put my custom texture and register the block in the creative inventory (without using custom models and material) if it's possible
You need to use a custom model even if it's just a simple cube that you are wanting to use. There may be other ways but last time I checked they were unreliable so we never added them to customies.

> And I wan't to create a custom id for my block, how can i do this ?
Why exactly do you want to do this? We have a PR open that will be getting merged soon which ensures block IDs persist even if the registration order changes, would that solve your problems?

**Comment by ShadowMikado** [comment]
Yes, thank you man
