### ISSUE TITLE
Bug of terrain generation

### ISSUE THREAD

**Issue by noxi69** [CustomiesDevs/Customies#39]
![image](https://user-images.githubusercontent.com/42916628/192804300-6a4514fc-c5b8-4397-aef9-b7d4f333a334.png)

Look how look like my world after putting Customies plugin on my server.
Can you fix it pls i use the latest version of your plugin :) 👍

**Comment by noxi69** [comment]
I check and it's just when i register a block that the world bug like this
```
 $creativeInfo = new CreativeInventoryInfo(CreativeInventoryInfo::CATEGORY_NATURE, CreativeInventoryInfo::GROUP_ORE);
        CustomiesBlockFactory::getInstance()->registerBlock(SapphireOre::class, "Minerais_Sapphire", "Minerais_Sapphire", new BlockBreakInfo(1), null, $creativeInfo);
```

**Comment by Unickorn** [comment]
Can you send a list of all the plugins you are using? Does the issue persist if you only load customies without any other plugins?

**Comment by TwistedAsylumMC** [comment]
This does seem to be an issue with your generation plugin, [SpectreZone](https://github.com/jasonwynn10/SpectreZone) uses custom blocks with world generation and does not have these issues.

**Comment by xLordShadow** [comment]
Im also having issues with the block mapping after registering a block.

If I dont have the block register it works fine, but after registering 1 block, it changes the blocks in the whole world when I get back on. 

My registering code: https://gist.github.com/xLordShadow/1a8c1793add0a87a420318f9bf74d328

**Comment by jasonwynn10** [comment]
This appears to be an issue specifically with introducing vanilla blocks rather than custom blocks. The process is different for vanilla implementations and should in no way be done through Customies to prevent the client-side block palette from being corrupted

**Comment by TwistedAsylumMC** [comment]
Due to what jason has said, this issue is being marked as wontfix. Customies is not compatible with plugins that register vanilla blocks that PMMP does not support, and that is mentioned in the README.
