### ISSUE TITLE
Block meta

### ISSUE THREAD

**Issue by PrograMistV1** [CustomiesDevs/Customies#40]
How can I create a custom block meta? i need to create about 25 variations of one block and it would be better to leave it with one ID.

**Comment by TwistedAsylumMC** [comment]
This is something we still need to work on; Minecraft has a permutations system but it's a really terrible system and not the easiest to design an API around. The best way to do this right now is to just register 25 different blocks unfortunately

**Comment by PrograMistV1** [comment]
Well thank you. Will wait

**Comment by TwistedAsylumMC** [comment]
No worries. Going to keep this open as a reminder though.

**Comment by unickorn** [comment]
Closed by 121eea9d86ad912cccc3398045fe10f23c181471
