### ISSUE TITLE
AsyncWorker#0 thread/CRITICAL bug

### ISSUE THREAD

**Issue by ShadowMikado** [CustomiesDevs/Customies#50]

**Comment by ShadowMikado** [comment]
When I start my server an error appears: `[AsyncWorker#0 thread/CRITICAL]: ArgumentCountError: "Too few arguments to function customiesdevs\customies\util\Cache::__construct()`

**Comment by Unickorn** [comment]
Thank you for the issue report! We will be working on this ASAP.
