### ISSUE TITLE
Items with a predefined stack value can be stacked above the value

### ISSUE THREAD

**Issue by ShadowMikado** [CustomiesDevs/Customies#53]
Hello I found a bug, when we create a item and init this item with a max stack size, like this, 
``` php
//
$this->initComponent("my_item", 1, $creativeInfo);
```
In the game, when we drop this item with the same item, they stack

An example:
![The video](https://user-images.githubusercontent.com/89030950/198322947-91106be6-6df8-4765-8bd7-53f3d24d3284.gif)

**Comment by TwistedAsylumMC** [comment]
You need to also tell pocketmine about the max stack size using the `getMaxStackSize()`, the value you provide in the component is just to tell the client what it is.
```php
public function getMaxStackSize() : int{
	return 1;
}
```

**Comment by ShadowMikado** [comment]
It work thanks TwistedAsylumMC
