### ISSUE TITLE
entity runtime identifier(bid)

### ISSUE THREAD

**Issue by DaisukeDaisuke** [CustomiesDevs/Customies#54]
> I use deepl translations

Customies Entity api does not have the option to add a bid (string).
This helps to invoke hard-coded behavior.(e.g. `minecraft:arrow`, `minecraft:shulker`)
https://wiki.bedrock.dev/entities/runtime-identifier.html

https://github.com/CustomiesDevs/Customies/blob/36f01b6102cc4e7170071e10a3eb27fcfa187071/src/entity/CustomiesEntityFactory.php#L27-L32

```php
->setString("bid", $bid)
->setString("bid", "minecraft:shulker");
```
https://github.com/CustomiesDevs/Customies/blob/36f01b6102cc4e7170071e10a3eb27fcfa187071/src/entity/CustomiesEntityFactory.php#L39-L45

**Comment by TwistedAsylumMC** [comment]
This is now possible with adfe37107cf4f1cc67866f9fba81f4ffe4e00b6f
