### ISSUE TITLE
Block turning in to update block when placing

### ISSUE THREAD

**Issue by LotchMc** [CustomiesDevs/Customies#55]
https://youtu.be/5jU_2WO81yY

**Comment by TwistedAsylumMC** [comment]
I am unable to reproduce this issue, could you please attach your code and make sure you're not doing anything that could be causing this?

**Comment by LotchMc** [comment]
const DURABILITY = 3050;
    const ATTACK = 9;

    public function __construct(ItemIdentifier $identifier, string $name = "Unknown") {
        parent::__construct($identifier, $name, ToolTier::DIAMOND());
        $this->initComponent("etain_sword", 1, new CreativeInventoryInfo("equipment", "itemGroup.name.sword"));
        $this->addProperty("hand_equipped", true);
        $this->addProperty("damage", self::ATTACK);
        $this->addComponent("minecraft:durability", CompoundTag::create()
            ->setTag("damage_chance", CompoundTag::create()
                ->setTag("max", new IntTag(100))
                ->setTag("min", new IntTag(100))
            )
            ->setTag("max_durability", new IntTag(self::DURABILITY))
        );
    }

**Comment by LotchMc** [comment]
const DURABILITY = 592;
    const PROTECTION = 8;

    public function __construct(ItemIdentifier $identifier, string $name = "Unknown") {
        parent::__construct($identifier, $name, new ArmorTypeInfo(self::PROTECTION, self::DURABILITY, ArmorInventory::SLOT_CHEST));
        $this->initComponent("cobalt_chestplate", 1, new CreativeInventoryInfo("equipment", "itemGroup.name.chestplate"));
        $this->addComponent("minecraft:wearable", CompoundTag::create()->setString("slot", "slot.armor.chest"));
        $this->addComponent("minecraft:armor", CompoundTag::create()->setInt("protection", self::PROTECTION));
        $this->addComponent("minecraft:durability", CompoundTag::create()->setInt("max_durability", self::DURABILITY));
    }

**Comment by AzOxStOz** [comment]
Twisted ?

**Comment by TwistedAsylumMC** [comment]
This is the same logic I used as well. Could you try again with a server that only has Customies and this item registered?

**Comment by LotchMc** [comment]
yes, i go

**Comment by LotchMc** [comment]
I managed to fix this bug but now I have another bug with CustomBlocks

https://youtu.be/RJrP1o7_0no

**Comment by TwistedAsylumMC** [comment]
Could you attach the code you are using to register these blocks, and could you also try disabling all your plugins apart from customies and the one used to register the block?

**Comment by LotchMc** [comment]
This is my block: 

$material = new Material(Material::TARGET_ALL, "cobalt_block", Material::RENDER_METHOD_ALPHA_TEST);
        $model = new Model([$material], "geometry.block", new Vector3(-8, 0, -8), new Vector3(16, 16, 16));
        $creativeInfo = new CreativeInventoryInfo(CreativeInventoryInfo::CATEGORY_CONSTRUCTION);
        CustomiesBlockFactory::getInstance()->registerBlock(fn(int $id) => new CobaltBlock(new BlockIdentifier($id, 1), "cobalt_block", new BlockBreakInfo(3.0, BlockToolType::PICKAXE, ToolTier::IRON()->getHarvestLevel())), "minecraft:cobalt_block", $model, $creativeInfo);
        
        And it is my class 
        class CobaltBlock extends Block {

    public function __construct(BlockIdentifier $idInfo, string $name, BlockBreakInfo $blockBreakInfo) {
        parent::__construct($idInfo, $name, $blockBreakInfo);
    }

    public function getDropsForCompatibleTool(Item $item): array
    {
        return [ItemFactory::getInstance()->get(1, 1, 1)];
    }

    public function getSilkTouchDrops(Item $item): array
    {
        return [ItemFactory::getInstance()->get(1, 1, 1)];
    }

}

**Comment by AzOxStOz** [comment]
twisted ?

**Comment by TwistedAsylumMC** [comment]
I don't see anything wrong with your code, did you test this with only Customies and the plugin registering these blocks? Please attach a picture of the output from `/pl` just to be sure

**Comment by AzOxStOz** [comment]
@TwistedAsylumMC can you send a template plugin for du this more easily please

**Comment by AzOxStOz** [comment]
ok twisted, we have a problem, when we do a simple plugin to add one block, it's work but, when we add an other block, it place the block UPDATE, but UPDATE it just a textures
