### ISSUE TITLE
Broken block registration

### ISSUE THREAD

**Issue by Kybomaster** [CustomiesDevs/Customies#56]
Problems occur when registering a block. The block is not added to the creative, if I put it through setBlock(), then I can take it with the mouse wheel, the client sees it as an empty slot

`
<?php

namespace Stones;

use customiesdevs\customies\block\CustomiesBlockFactory; 
use customiesdevs\customies\block\Material; 
use customiesdevs\customies\block\Model; 
use pocketmine\block\Block; 
use customiesdevs\customies\item\CreativeInventoryInfo; 
use pocketmine\block\BlockBreakInfo; 
use pocketmine\block\BlockIdentifier; 
use pocketmine\math\Vector3; 
use pocketmine\plugin\PluginBase; 
use pocketmine\inventory\CreativeInventory; 
use pocketmine\item\ToolTier;
use pocketmine\block\BlockToolType;
use customiesdevs\customies\item\CustomiesItemFactory;
use pocketmine\utils\SingletonTrait;

class MainStones extends PluginBase{

    use SingletonTrait;

    public function onEnable(): void{
        
        self::setInstance($this);
        $this->registerBlocks();
    }

    private function registerBlocks(): void
    {
        
        $model_id = "geometry.block";
        $material = new Material(Material::TARGET_ALL, "blackstone", Material::RENDER_METHOD_BLEND);
        $model = new Model([$material], $model_id, new Vector3(-8, 0, -8), new Vector3(16, 16, 16));
        $id = "minecraft:tuff";
        $creativeInfo = new CreativeInventoryInfo(CreativeInventoryInfo::CATEGORY_NATURE);
        CustomiesBlockFactory::getInstance()->registerBlock(fn(int $id) => new Tuff(new BlockIdentifier($id, 0), "Туфф", new BlockBreakInfo(5.0, BlockToolType::PICKAXE, ToolTier::STONE()->getHarvestLevel())), $id, null, $creativeInfo);
    
        $id = "minecraft:cobbled_deepslate";
        $creativeInfo = new CreativeInventoryInfo(CreativeInventoryInfo::CATEGORY_NATURE);
        CustomiesBlockFactory::getInstance()->registerBlock(fn(int $id) => new CobbledDeepslate(new BlockIdentifier($id, 0), "Глубинный сланец", new BlockBreakInfo(5.0, BlockToolType::PICKAXE, ToolTier::STONE()->getHarvestLevel())), $id, null, $creativeInfo);
    
        $id = "minecraft:calcite";
        $creativeInfo = new CreativeInventoryInfo(CreativeInventoryInfo::CATEGORY_NATURE);
        CustomiesBlockFactory::getInstance()->registerBlock(fn(int $id) => new Calcite(new BlockIdentifier($id, 0), "Кальцит", new BlockBreakInfo(5.0, BlockToolType::PICKAXE, ToolTier::STONE()->getHarvestLevel())), $id, null, $creativeInfo);
    
    }

}
`

**Comment by zTheusL** [comment]
Delete your idcache into your customies plugin_data

**Comment by Kybomaster** [comment]
> Delete your idcache into your customies plugin_data

It helped, what is the essence of the problem?

**Comment by TwistedAsylumMC** [comment]
> > Delete your idcache into your customies plugin_data
> 
> It helped, what is the essence of the problem?

I am not yet aware of what causes the cache to corrupt blocks like this, but since your issue is now resolved I will close this issue.
