### ISSUE TITLE
bug when open server

### ISSUE THREAD

**Issue by TeamSinkong** [CustomiesDevs/Customies#57]
![image](https://user-images.githubusercontent.com/73025791/208407703-65c6834a-bb54-4107-8ffd-95f4d8beba32.png)
Just when i put it on it got this error.

**Comment by TwistedAsylumMC** [comment]
What version of pocketmine are you using?

**Comment by TeamSinkong** [comment]
> 
version [4.12.1] But bring it back and modify it as my own.

**Comment by TwistedAsylumMC** [comment]
Customies is only made for the latest version of pocketmine and will not ever support unofficial forks. It works on the latest version, so I will close this issue as it's invalid

**Comment by TeamSinkong** [comment]
ok thanks
