### ISSUE TITLE
Sending it back to my class surely doesn't work 

### ISSUE THREAD

**Issue by mentagess** [CustomiesDevs/Customies#58]
hello I contact you because I think I made a mistake I have trouble doing it, I put this code below that I developed from your wiki but it does not work the item created but go but go to another category and don't equip yourself at all, there is no error on the console 

Main.php

`      	CustomiesItemFactory::getInstance()->registerItem(Item::class, "customies:casque_solarium", "Casque en Solarium");`

Class
`<?php

namespace Mentagess\Item\Armures\Solarium;

use customiesdevs\customies\item\ItemComponents;
use customiesdevs\customies\item\ItemComponentsTrait;
use customiesdevs\customies\item\component\AllowOffHandComponent;
use customiesdevs\customies\item\component\ArmorComponent;
use customiesdevs\customies\item\component\MaxStackSizeComponent;
use customiesdevs\customies\item\component\HandEquippedComponent;
use customiesdevs\customies\item\component\WearableComponent;
use customiesdevs\customies\item\CreativeInventoryInfo;
use pocketmine\item\Item;
use Mentagess\Item\Main;

class CasqueSolarium extends Item implements ItemComponents {
	use ItemComponentsTrait;

	public function __construct(ItemIdentifier $identifier, string $name = "casque_solarium") {
		parent::__construct($identifier, $name);
    $creativeInfo = new CreativeInventoryInfo(CreativeInventoryInfo::CATEGORY_EQUIPMENT, CreativeInventoryInfo::GROUP_HELMET);
    $this->initComponent("casque_solarium", 1, $creativeInfo);
    $this->addComponent("minecraft:armor", ["protection" => new IntTag(2)]);
    $this->addProperty("allow_off_hand", true);
    $this->addProperty("hand_equipped", true);
    $this->addComponent("minecraft:wearable", ["slot" => "slot.armor.head"]);
	}
}`

**Comment by Gewinum** [comment]
which customies version is this

**Comment by Gewinum** [comment]
to which category does it go? you have to implement equipping yourself

**Comment by mentagess** [comment]
it's good I solved the problem now I can't configure my data when I put this it gives me an error every tdata
`  $this->addComponent("minecraft:armor", ["protection" => new IntTag(2)]);
    $this->addProperty("max_stack_size", 1);
    $this->addProperty("allow_off_hand", true);
    $this->addProperty("hand_equipped", true);
    $this->addComponent("minecraft:wearable", ["slot" => WearableComponent::SLOT_ARMOR_HEAD]);`

**Comment by mentagess** [comment]
if you can give me a corrected version of this please because I tried everything I did not succeed yet

**Comment by Gewinum** [comment]
download last customies version from poggit, i will not provide any help to you, because your customies version is old, not the latest

**Comment by Gewinum** [comment]
ah sry i checked something im little wrong your customies version is the latest

**Comment by Gewinum** [comment]
> it's good I solved the problem now I can't configure my data when I put this it gives me an error every tdata ` $this->addComponent("minecraft:armor", ["protection" => new IntTag(2)]); $this->addProperty("max_stack_size", 1); $this->addProperty("allow_off_hand", true); $this->addProperty("hand_equipped", true); $this->addComponent("minecraft:wearable", ["slot" => WearableComponent::SLOT_ARMOR_HEAD]);`

what do you mean "error every tdata"

**Comment by mentagess** [comment]
hey my problem is solved it was the problem of my api I was using the wrong one. That of github instead of that of poggit. On the other hand now I have a problem of a client error here it is.

```
Failed to validate components of item "customies:pioche_solarium" due to the following
-Failed to validate component "minecraft:digger" 
``` 

My concerned part of code 

```
        $this->addComponent("minecraft:digger", ["destroy_speeds" =>
            ["block" => [
              "tags" => "query.any_tag('stone', 'metal', 'diamond_pick_diggable')"],
            "speed" => 8,
            "on_dig" => [
               "event" => "on_dig"]],
            "use_efficiency" => true
              ]
           );
```
