### ISSUE TITLE
Add support for PM5

### ISSUE THREAD

**Issue by supercrafter333** [CustomiesDevs/Customies#61]
Hello,
can you add support for PM5, please?

**Comment by Gewinum** [comment]
> Hello,
> can you add support for PM5, please?

less likely it gonna be supported until pm5 goes out of alpha

**Comment by royaljacques** [comment]
I think it's time to at least look into it. opens a temporary branch. many servers use this plugin and would be severely impacted if they can't update it. very little developer happens to do what this plugin do.

**Comment by DuoIncure** [comment]
If someone really needed it, there is an *unofficial* pm5 fork here: https://github.com/DavyCraft648/Customies-NG

But due to it being a fork and on an unsupported api version you probably wouldn't find much support if you were to encounter bugs with it.

**Comment by TwistedAsylumMC** [comment]
This is implemented by https://github.com/CustomiesDevs/Customies/pull/71. You can use this branch until PM5 releases
