### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by EmporiumPvP** [CustomiesDevs/Customies#67]
PocketMine-MP Crash Dump Tue Mar 7 23:38:08 UTC 2023

PocketMine-MP version: 4.16.0 [Protocol 567]
Git commit: fa131dab1259c25d48c41b4ce82de5f833eb0326
PHP version: 8.0.28
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Customies

Error: file_get_contents(phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/bedrock-data/block_id_map.json): Failed to open stream: phar error: "vendor/pocketmine/bedrock-data/block_id_map.json" is not a file in phar "/home/container/PocketMine-MP.phar"
File: plugins/Customies.phar/src/world/LegacyBlockIdToStringIdMap
Line: 24
Type: ErrorException
Backtrace:
#0 (): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[255] file_get_contents(phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/be, string[86] phar:///home/container/plugins/Customies.phar/src/world/LegacyBlockIdToStringIdM, int 24)
#1 plugins/Customies.phar/src/world/LegacyBlockIdToStringIdMap(24): file_get_contents(string[90] phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/bedrock-data/block_i)
#2 pmsrc/src/utils/SingletonTrait(31): customiesdevs\customies\world\LegacyBlockIdToStringIdMap->__construct()
#3 pmsrc/src/utils/SingletonTrait(36): customiesdevs\customies\world\LegacyBlockIdToStringIdMap::make()
#4 plugins/Customies.phar/src/block/CustomiesBlockFactory(225): customiesdevs\customies\world\LegacyBlockIdToStringIdMap::getInstance()
#5 plugins/Customies.phar/src/Customies(31): customiesdevs\customies\block\CustomiesBlockFactory->registerCustomRuntimeMappings()
#6 pmsrc/src/scheduler/ClosureTask(57): customiesdevs\customies\Customies::customiesdevs\customies\{closure}()
#7 pmsrc/src/scheduler/TaskHandler(123): pocketmine\scheduler\ClosureTask->onRun()
#8 pmsrc/src/scheduler/TaskScheduler(141): pocketmine\scheduler\TaskHandler->run()
#9 pmsrc/src/plugin/PluginManager(530): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 1)
#10 pmsrc/src/Server(1808): pocketmine\plugin\PluginManager->tickSchedulers(int 1)
#11 pmsrc/src/Server(1697): pocketmine\Server->tick()
#12 pmsrc/src/Server(1056): pocketmine\Server->tickProcessor()
#13 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#14 pmsrc/src/PocketMine(362): pocketmine\server()
#15 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[15] 	private array $legacyToString;
[16] 	/**
[17] 	 * @var int[]
[18] 	 * @phpstan-var array<string, int>
[19] 	 */
[20] 	private array $stringToLegacy;
[21] 
[22] 	public function __construct() {
[23] 		/** @phpstan-var array<string, int> $blockIdMap */
[24] 		$blockIdMap = json_decode((string)file_get_contents(BEDROCK_DATA_PATH . "block_id_map.json"), true);
[25] 		$this->stringToLegacy = $blockIdMap;
[26] 		/** @phpstan-var array<int, string> $flipped */
[27] 		$flipped = array_flip($this->stringToLegacy);
[28] 		$this->legacyToString = $flipped;
[29] 	}
[30] 
[31] 	public function legacyToString(int $legacy): ?string {
[32] 		return $this->legacyToString[$legacy] ?? null;
[33] 	}
[34] 

Loaded plugins:
BuilderTools 1.4.0 by CzechPMDevs, VixikHD for API(s) 4.0.0
Customies 1.2.0 by DenielWorld, TwistedAsylumMC for API(s) 4.0.0
DevTools 1.15.0 by PocketMine Team for API(s) 4.0.0
EmporiumCore 1.0.0 by Tetro for API(s) 4.0.0
EmporiumPrison 1.0.0 by  for API(s) 4.0.0
EntityAPI 2 by JonyGamesYT9 (iJonyMx) for API(s) 4.0.0
Fireworks 1.0.0-PM4 by  for API(s) 4.2.0
InvSee 2.2.4 by BlockHorizons for API(s) 4.0.0
MiniBosses 3.2.5 by diamond-gold (ace) for API(s) 4.14.0
MultiWorld 2.0.0-beta1 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 4.0.0
PersonaAdapter 1.0.0 by Lunarelly for API(s) 4.0.0
PlayerVaults 3.5.0 by  for API(s) 4.0.0
Tutorial 1.0.0 by Emporium for API(s) 4.0.0
WFT 1.3.6 by WolfDen133 for API(s) 4.10.0
Wormhole 1.0.0 by Emporium for API(s) 4.0.0

uname -a: Linux a70208aa-45b4-4163-98c0-49c52e5d39f7 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64
Zend version: 4.0.28
Composer libraries: 
- adhocore/json-comment 1.2.1@651023f9fe52e9efa2198cbaf6e481d1968e2377
- brick/math 0.10.2@459f2781e1a08d52ee56b0b1444086e038561e3f
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.5.0@42060ed45344789fb9f21f9f1864fc47b9e3507b
- netresearch/jsonmapper v4.1.0@cfa81ea1d35294d64adb9c68aa4cb9e92400e53f
- pocketmine/bedrock-block-upgrade-schema 1.1.0@78c965a2316986ac0eaf3235d75efb187127e7a2
- pocketmine/bedrock-data 2.0.0+bedrock-1.19.60@957e49b2381641af29f595e4f32ded3e76ce4723
- pocketmine/bedrock-item-upgrade-schema 1.0.0@7e53f77ea34ba30b1f94d3c24e64e19d3c4296e7
- pocketmine/bedrock-protocol 19.3.0+bedrock-1.19.62@a5bf4753c7f30f781c4541918e238f5bb637e7ad
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.3.0@8cb346d0a21ad3287cc8d7175e4b643416607249
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.18.3@da25bfe9ee4822a84feb9b7e620c56ad4000aed0
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.3@47a243d320b01c8099d65309967934c188111549
- pocketmine/nbt 0.3.3@f4321be50df1a18b9f4e94d428a2e68a6e2ac2b4
- pocketmine/pocketmine-mp 4.16.0@fa131dab1259c25d48c41b4ce82de5f833eb0326
- pocketmine/raklib 0.14.6@aeca667d5ecc4cc18fded612f29e3511bbf62f42
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.3.0@ad7475d1c9e70b190ecffc58f2d989416af339b4
- ramsey/uuid 4.7.3@433b2014e3979047db08a17a205f410ba3869cf2
- rhumsaa/uuid unknown@unknown
- symfony/filesystem v5.4.21@e75960b1bbfd2b8c9e483e0d74811d555ca3de9f
- symfony/polyfill-ctype v1.27.0@5bbc823adecdae860bb64756d639ecfec17b050a
- symfony/polyfill-mbstring v1.27.0@8ad114f6b39e2c98a8b0e3bd907732c207c2b534
- symfony/polyfill-php80 v1.27.0@7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936
- symfony/polyfill-php81 v1.27.0@707403074c8ea6e2edaf8794b0157a0bfa52157a
- webmozart/assert 1.11.0@11cb2199493b2f8a3b53e7f19068fc6aac760991
- webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtfHt320Z691eZyj4n0lagcCNIcCuvHMlu/NauVUuutw19nAEwIBGBAIOLJGZPvvv7e54ZgCAt
27m4Pf0jm01EDGaeee63GfIfB2lZrWTz4VZVdVYWBzP/+KDJVupg5gSTqeu57nQ6mri+F4THB+1a
v7JHE89zJ649GQdjz54E7vFBLuvmWVWV1cHsHwfNZo1pB/z87D5WWAfYxwcrVddyQa/SLFcfFqr5
EJdFo4qmPlwvZTU7OTlZlit1QqMyK1R1clnGN6p5hc/Wq8sRTTq5VUVSVidrfrPCm5NIJRWerEQ2
8iTK8fFDlnxYyfXox7osjmbiucR+iWhKUa5VIeqmUnI1EwROKMJyJuYHvxXu/EBktSjKRkhB9Iis
0BDnB1+mYn4AfqRtnj/HSjDkE+Sv83aRFfXJeVs35SpTtWZBXcUnd2WVJycv1ULGm28JtxfJdXnV
VFmxeJG8Ao7r5Zr2MPB/PyAAyYHMwcwl5ahkjI/fHzyyxSE4u+XWfM6cXMoiyVU1n7P0r8te/t/p
F7OZnnGYFY1wj0kW2Oh7dzx+L762VvTQp8F78bU5fCyYAv8I/HnkiD/A4EMAmT1AvEE+tD+J/O+2
DkbaFesV4Uf/tk2W1ydX2C9XTVlcVzJrDj0HeMUdQYm6refz/nE+Z7rm808TZj35QNSAjjZuDnlP
74t7Bn9sz9lsJW+U3sz/nFSYE9sXDOu5jJuy2hy67viPYgFJvgDlsogNMuPPIdMPfYnnjPV8/iDa
1pNKLbK6UZV+/aYtyGEDnTXwqjUawUAAdbxUSQujPDnPy7qt1LWsbw7Hk89i0G89m3160j9iDfAX
venkwU1pN+MVDh3X2/Mm/TxsucXOelIWoEuDnX4S7FX3dOj4zqcBDzAA8zqw4QCsltnJJf95JQuE
r+oQQe/zMPvtrScrWOr1EvEm+U7JqomUbNj1Odpv2IO9rlR1SxhP7ekeeI3FfL6DhvWkyeLtVvUQ
rPMA2CCc7IHVbzQcTbrjPrDQHgefWXgJ54K4XlYGwtDCt/7p0PPCTwAZ+ogy+lHFjfhW1uocKUX9
spSJqh6Nj4V5MwTA/mM+fwUOvywX4MijbTxx4PH3veU22Pgfv+yMUxPhf4KIwN0XvOaRXjXWqw4d
UrlK/dRmleq8ePCbvPjuvhTKjw7e/3J8oP5MsX5jivU10x8IQAP6kBW3ZX6rVuAroCeQc9wcdG8x
0u+DwbhMFInMGePFvFlX2a1slJBVJTficc4bdzv+FfOdgOed/OUv9DDhB/EXcXYLumHi37+n4Wk/
DN2gMGPRa4b5L1rjOD95QnNDM/cED679EBJ6xXWpuUBIuA7m0V9Xz2+jPItF2hYxKZrYieviHzTR
44mM95eQEo8jzWiw16Dlm9XDN6eCdOBDooiDh8aQjj7W62+fXbx5ff5vHy6eXj/9cPn0+jsxgoI8
oExHxwIoqyMmcNzt2Cyz2nqyywLsPcCE5wefpw90df4F9KV5tl7DHDRxk26rbvhUL/pAz4cPIqBx
nO7iuKsrhKMByJO1mH/BR8/WwvOcB4W3C4bDhlFD2PHfNB4sU881+1eqaatCPIjG92bte/G3v4kC
FQ0h43lbZEi0B7/8WTr8WTr8WTr8WTr8WTr8WTr8WTr8b5cOXWpaUyL6bZvlYM11Web8XEjq6u4O
Hx/0LeEDZ+SPbIzItlmWVU0h/PxnFS8vX13AePHiP7P77Oa7C9pGrjN6jwVYgmdVyAh1wcGMEq/j
g0ShOEgIBN7VZdpcDAdI4bFfTMDXK+0ZIo1VQ1jN53s45pAxFly+vrp+9/rNywsM3amozhqiZ9k0
6xo8W2TNso1Gcbk6GaB9sgMK6ck2Zd+yZJjGD/nh7vPjQhWZyt+Rb8eL6ztypcnTepO3q1fnX40v
X3asX+IJEQrq90XfD+2S6Yz36dwqlrhGffe1KOv2n88HmBhCrq6fvrl+e/kl0W4xO+lhgNhnq3VZ
Ze3qvKzUgOCd4V2i7X2ar1VTlV+L0uHGSHR30fii6Lr5l1VWE7of0WNefJ6i30LKLqd+BWGINIzD
lrgepy+Th6Sj2Ty9fDGkrB8bEuXuiuj/lcXmXzG//q/rUBxm9Pjq/uhryWwIHWR1CA0+/hrinsOj
I/m7GdrdduwjiVmXr/xPSs39/cRw1vcdBPMzIud83mOAlJQD5q8h5UVxe6WG5mQGdiQEJHcJ2N36
awlnjx6NyW8hBi4j+7as6x3HPxgcEuWBqPEuUUkmV2WRWIsyT8QhKtxdtXP830+aAU2Qkar0GOm0
5XdEvyGqJwMKiQlt3mQ6fA2YsB3clSypZ6Qa6XwxKTj/bz7m3LRN3d5k+Hwj8yy7qf9HUoUV4Wvq
qx3c/0iaMAAEPl2CC2UhnyZyjVppwKu9F18IKS/bQlYqzzdfiw95BxAJv8ZEakyQK99QjvtrrOEB
TmwRJeJzuVHVf0pwZGgrO8O71jL+A5HnM9Su2p+AMtU2tPMt70wVzg4eXzT86xaVbybzASn90Bfk
14W2g98VSk1A/AyBnHIgvlx2CP0Wh/bu+fWAJHrapcYbBbvUvCvzFAms43m7rusPSGgLcj4HBvyf
X4V7Wa2WZT6MLf3Q/4RMflVC02Gw/fRlUuioQFagADbI6I0eqNWwxrKK0rrLfpZVwk9JVhOqlizq
jDG/b1RBRLPF6Sz2YAq63CnmJ7LZec6z6H6VD0foMKaud4bW8S6Q+qccWHvDoZ8BaPgcxSvZLIcj
sczBMZAwHFu2xQ1X1tQ3tqFoHo1Wm3VTmgHK22JzdrVd11Y7CCblisKMbXuO44bmECcr0nI4CWPs
gQcjzXr4uEh2nlY7L5ey3iGHum0JyWAw9iOn2APmqluVJ5GhxNbsTlSaayHYI4cHV5Eu24dLVyUK
2MJMIh6sNuB6QduZT6Kfe3X5cldaRbPDHV6QDUcuL17vrEjKDzxpf1ALemflcleC67LO7nf4wjpb
78xpuCVFY5SIUg5QKYiQlHTRah52vHgD7ig+dNgBulyVO9K4ylbrXP391Q7h2SLKEHw2Ju1ySJea
8gaF9s+7ct/TeDwSfh/NuauyPYW5vzdqQOgSHRvJoCh1JSH9nK11GRxy0vffUHjx+jKW8XLARBj6
j1nzYcWHfDbYs1wbVSWtU4WqdiLMjhMgy5K12t6+I68bMOe47XEwcx13ClbUH5DhHMxSmddwX+uq
bMq4BNhxMMEmGZ1BptLxnERGjjsOY3ec+NPYdyI/VlM3UeN06nkqsj2XXH9rcHmZFe29kBPbtadS
Wv448i3fCTwrnMa25Yfx2FXjxAvTiRhTC8gCbItJymLxyPEd623UFk0rrl5dincqEU/bhXBs4Xgz
353Znnh7fS5c23XF/TT4EFA1QHfShn5GsQ34vW4t1x/KukON3Bc95OYBCQkUVFUfYHeVrEyrRiZL
MKNSJ2SvFuaYQ1nq0jhnwdixXS8NUwViQpVK1wF1kUwD5U+dxAmDqXK9yYRYDrJuToyjsyn8uWf+
OEzdydRRjrSnCUCocRDZkeP7vj0NlO1Nx4GjvJR9McQIL4KsCc4xj2R8Y90i24WPpiN7cP2mKO+K
M/OXHNaiogT8BFTLuqCzuluXUqYz37UDWyX+2PP9yTRMIyDhgAZnGvhp7E+iUHljexIBRoFMQdVK
VvGSGbCS6zVr+a1PNngWpxLYSyfxxm7oJ4EvkyiMA8jbjwEmdH3bVmMm4IFzHz4ysNr1ooJBWdSp
XkltEgA9mcZhMJau5wThNJCxrWTqud44mYxVGjnTieNO1ES6D4OmI6WumPjnbpBtLbDPwvFE+WHk
elMn8B2ZumE6DsfKB/xEJZ6aBLHyJ673MGjY+eohpG1CmoidTJT0/Eh6kGQKrnix66vAV06Ij74b
BmryMOSt5R0AUe8jzN0zOY5SfzL24knq2Sk0J/bHvhM6pGXTdBxFgUdMSfbgs6fj0Mm6h9L5bCzj
iVIyBPmRTKZJ7IcAECsPNh244SQZqwCv5S6kB1WPSPfOAujSxA/CSRBEsZTgxHQ6dn1XTcexCxaM
1TQej/flFVMvPS+NQyXUoJ8h+Gd7YeipNEkjL4wTz3aV64yDZGwD9NS1QzWZ7kEq87LqoucZjNDz
g8SGQcrEc6eTOJ4mEwe640eB78EPBfbE9cNdGMNzYgYFb3mWSGztSxurplHoOHB5TqiiFO4qTR3Q
NA0BfB8dqDZymK0eOlPwKJEuBAhHAe/gunLqpyoKowkYbsfjQCawFluqxN4HtWBk4MfOVBCHjhvb
aWiPxzFcDOzDnqrYTZxJGIVB6tt+DFQ/gmANAqsGFTjpBHycxqkHiZGO+ipVtitjGEEwtaUTQ6vi
PV3qHZgPenzYn++Bv3ZkO/HUDsOErmyHYTAJoUjOdOo4znify0XUdAncWep7rhOpsZ2kjnTA39RX
MBnfnUpXwY8ECvi4kb8LYfvR4sRLx7Wz3xCkBsAqeaPzUZvaKcGZVLEMAjKAOPZjEJESPxwXbgJ+
0XGiKA3c1HcfgmJl67iL+GchRBzAlUd2HMSTREo5pv9PQbE9UY6Cq/WmEPcuoLooy5+VYZBzZst4
msauZFt3Qumk8CQwMD8ZT+GlXRhtqNyQnDXqgVptyBC2WZHD1iCTCbxG4sQwGzil0FZxmsbjaeom
4TSEMcC1eiFz2QBp20yHzgmJ2fMi13Z85YWT0PYnSYSI7kD29jj1HRuebhqEcUocqZbtqpayW/9x
VKo3q7QsNieUdNebGr6UogklAK5zpibjMACCYHHiRggAsBNP2cAeipSMofHSS1SYDuCsy3wDWLnV
5f23iMwT0AxnGE9dD54lhgVPARaGP4ELCbwQ5KvYmUQ23MlDsAZJdgduKhPH8dMA7ki5cTiV08hW
XpSE9mTiubFrT6CmiKgPgUMEntoDWBMZpKmXOuE4jGA4UqVxHPmBJ+3Uha/DP26ahF7wKVjOEJY9
8W0P/4mniqxFJTKdTkIonTOeSDtK5dilT7qAXJUoBZsT+FxV6SzGoVjrOHEEpxb6IQSdTqUHStQE
CNoBlC+QiBUBrNrZAbKGJ7AoqLB/IzUDzsjmVAJfEkNTI6QCdoKcJgajkykCATaA1x3r+rVX+dGG
8+JHghqPIi6LNFu0leTLRHwtLy0rsZPZzotH4nqJxETUqmnoCoGQlRLNUomyUDU+yEbEsqCrfRFd
64vzFkZM9/v0segIoRaJTEPHW4B1Va6wMiUA+zBrmapjUeJNVRNIEcGL3ohN2VYGlshSgfw8SzPe
AckiXdfLNwT439VdD+4ExRx3j8RdWXzTCEql6H5X25RwqhmF1g1hSLegNN13S1UInWkAwGhezIsO
2GxeCPHo3VIRYnQtsqbyASDMSTJ4gGyxpuIx0a8ZVR2VBPiZq4b5hcw/i5XQQY9GVgQZHI+VlUsq
uRZqJrg0oBf1sm0SWLJlboLStUt9XC7oYoVK5geM2dM8L+9EntWEbXe/RNxmUvxHq6oNzfmJPljm
1WCLR8+4nWIWCSAmKAEXEBm4QuCijTC8pPm6+2L1r4eg3sFkoBJgrEwSgVRW85/4SjcExEpJur9B
OT1dBY0UYQ3uqJ9amRPfFtkt5iLbaZU4NJui6Dgi6HpHZVVqjQLcAt/pqH+G17z3v7erCGyBWj2t
N0VMty8EnYVAkUY84S3YxbrdUUrTllVZlC3Eh+n1seB+s9CFHhnEsaAyBYRQRce8gUHS2KotoEI0
RQO/YvmCJqhZVd5nUDEFNoAkVt2iR454axB6kZKy0hxSymORNd+AfU3FyxLV0DUH0pm9xeIQNLQw
HJfZwmRYhtIZg9pXVsnaUbVFQeJMqPNRrlkIXJjWI3Ghbs1nscoWS1hzhWL6eGh9RnOII1XVrhs9
qhlGjFkBN0MXCxdWydVboi1C3pZZArQfxoB0hHQOFVQG7RoNFA2TLT1pxvc9ySxXCrtttFH+a15G
UB5q/Ak9DjtYZQ3Z9kotZLRpwHBxpTltM291W46XX5PQ7jJmPCsUjPbO0oA6HauZwDQDhvBIQL5g
WGmlVLel1nEIqyUzFYsScirJTEkpaKMFo2kxajNhExXYnV2wzhT/z1NAndTP4b+UVfLH8K+bcs0o
GPfZo2TA1QLeY03RNOkRol33sWIH8I4twiBXf/MV0GObYHzIW4i4ReQpEHmEuldxy5631Phqa6RI
1c9W97FSSb0lRzut19fPZuL6uxdX4uWLVy+uxdPLy5cvnl2Jy2dvxLvXb/7t2ZtjgUni+jVmPRPv
vnv98pm4fPP6/NnV1Wjf/B9kxqWqspJjMbngmshDEc3OmHnRu1kHbEc2kLBX4SkWnKDSDpZBnZcF
qIRrhiIRtZ/SM61fd0sKqnRDGc5HT2PIGgic7taFd3aNPV5T9KAQzwtGH88mNTAnABDaWsWUCWi+
ErpaqnptTwM0S63rLamebWitjx5GyVDuGcoXsopgFNY212ff8zB32coIHbNKmFXw2itZtJx3DDFB
TtZCA4+Ou2iwr4KdEurAmiKXbjS9q631jcRr7e21uiNxKNs86XHJED7uCrHFv9aA14w+CA1QCmta
sdtz9hMfhUdWHQ2hpy2tylUXZvVqM8MaKuZQwkSNkeRHuiEeUKkd7bjqckUSWYWdSA2NIiftaq0T
K529CfPCohedvC5oklnAuDOaHQV4QoCHqcsHGIxwjZCHHW6hZHXdKnILzRJSW3SJJvkr2m2L1XEn
SJ0dmHxypLGhqZ/k00reW3wGU3e4n8s1jWardoXoisBaEXC+WUyCFPoAVWOx5SvZi2ElW8zHOoY8
e20w4g0tSoBbhFu/l9hFqV/t6zRlReTzNHw9uTMhDctMHFLGOYPFnfeetgugwlkKEkfiHrDTqYWG
spZUjgi9RlO4pQ7LDD/NcZvZmSZ3+2oG5lQBGLifB/U5PZwXhWpIYDMTIJCULenCCCWXkWziJSfh
jHJN3w4QJsSwb9NFj3mrA0uk+jRTR7ZHQyl1r8itVptmyV+8sZyBAFl4vLHVdMjAbY8D47W3GSyf
elHymGjKqYzhFJ8WY9CgNRLfIQuELp1yWifOL98eYy1wiGBfd1kCtec0QXvPHr7F8Gci6BLubS5e
M3cGc0fiaQJHtZR5eoIqUhcIiYIOm62wqaBWJSnYwBC3QW8AbKeeuSevRsmlzEeCkHh7WVx2afa2
9qMqgpC6Q9Ckhe26WFvmea+ueWWsrs5+Vr08KSHvxFhTwDPZEhJ2rR6D0OqHrl50NBKXZk0uqwUv
kKYINbrAO6aVXBAJkAnYVq9zzleoslwBeTJ2WZGczvOMviLCpTJdNFZ1I15dv2VMa5BEZEdtw9+6
Y1Fut9NlxajzNaumtWjVjLEdVoaq4FNftvVUUE8AmRBy1Y5MlL5pmsUjwVFqKSkJENkKvGlIdpAG
/y4F3NQx4wKh3TLSS+IEvC47YoRoye681iLVqQTmNkZHiRKlWwPG1Zk66uI1p0gXL66efovsiLOp
tmAdIofdkqfkI2GdJGSkjOYrf8mw0tjSubX1REXtYtaVa0+EQ2WayVaXcFf8XpjqvNb9BLLmoi51
8DYW4RAwjbWGdr4sUb+TFXZVmurqcPbi1MkWtbztogU+oujmd9zl3jo2QoxvQuikzbRjfiyzQvcC
mFPfiL9H5T1ZfiVeXIjDv799cXEEucPsgQPm30FsJJgM4R7GQdVblRj+6PQD1lBuZVfA2v/+7csO
vqnsBiPf8GZ0OMmJA4vXpCJMW9k1h0wYvQd+Ft0AOS3TlLfFuyzdWPdtlmwFwvy0dvsy19xY0aam
fwJF84A9vbGrtjYNnhhOpNFu1qyx9JqZMHcCaBsdQox7NLtQDJTFoi9PClqW74fi427WbaburD5A
P9QL08x9uipb8h6pjnXGmYBlHWsptpN35CYIxE+fOThj8RsO1YPFTHihdNEdKQ0sUinZfr2Wd6wU
pKMaOqsWDfdBX+e8mn7aqaf/o61kBcRR/Hcqiw07NOnvFuJef4bPIclW6izRfp9wkpALlKZuoyEl
CwqEmKESHf74oQ9P3CgyApZxrHLF2b5WUd41z26wBZW57E1yCW4sqvKuWWpfJOnLyEsNbeCoYMF1
o8MqI2sR3zvUrK0QNGkvLuoBXeRqSXoamtCnyD2ZpmHUpSr6THbIZ8CzgCKq3P4pi1X/mTL6rYC2
napZF6hGQu4rlPFKdzLjIhVRAjWcVo91uW7zzh7MAwVynmPigefShlzfEOm8E4VSckmI9aZyoBHT
m5uZHIZaiVwz62GdAqz114SAyNb1JltvRiZn0VeE94Z6i98dNhc0BsEahm7pu4/9zCWEOdOojNar
1XqUlYwxfNhmRVUfbLSh3mlcb1Gn+GPei+17JoH9l1wsKrUwXULTUtStE/pq7M0+fYwfnMjri9f0
lSDLeHsd+Mkv3SldWkhY7x3vWDPiWwJ4bDRo5CMA95xv13R9TAvnI6ZCoPq90TCkOHS5goPUIJCc
U79dDdtzx/D666WErShy2RXh0CWcCAWpqlBUWOTwCopy+m0XlHRIkDvtPnM5ZhBFWyTXSFrYaXa+
yQBkKev33R4fSVXTNRRrk622ocGEWQJK80nrKRKQFMk/04bcxzSLup71aLuBeTPcoePcR33WmL7i
zO1hSQpE/fdBOsAlpDH8BJwtdDIv6CQt6VpHZm5fGGQLhJkuDiOZTVtulJPtEbLAPaZUtBBL5Mac
8/RRlVuqQ5iU9JEX1QXAoRotRkwkHvSiY3FB2oW/qolHR4PcKCvWbTNUlU+lLyY2av3Vdj9ojHWY
NFljtKhrgS3NoPb2VU9/xy9BxlZpCrO0B0TXENpKnx2R4+06QzoIAZ5x1F36gBRT1qbsfKTzmtrU
sVx/6pSRZJlARBUqwFs+v8EnVN9GssJA0QQ8eipq/uqyHuZUnCoMOhujpZx267S11wxq4RsgRx0U
/UhJCWw7ESw95gLVFRWFSmjMPgqYHqOQwPxo05/77J/fwdhqlacj00ShTMZQJgsNSPeeMraP79+j
AKOwiXTvEDxVOhKTuWf3arszz5kPDhZn1L+dH2ikiWHdcZIsvtHtzkeRMjsnR1oEtGSGLTvUzjsO
dQI1049190vnjx37xX9BVsRuuGbeMjV22HNJu6CMQk+LGYcdEUd6N8pOjzldIJ0imdHUjkBCgXhP
dw1RhIxYSRkOrSNramvdzqvLldK2/DFTDCq0BLwpK73z3HyFk4Z3p2h1kBHFUfH9HnffD0RIR2xb
+dHZnzExBnZYH2m5ZQ1ro1F5Klowy7hhbGA+vddv4VWMRLjewLpjsb8vlU43pDo7Oq2TeJS0Lfl5
IERu9jF3Kahjz6ghdwGS3Zxj8dhlR6w7/tSOJbej8aSDQJmAbqBSrgHoPTYXP/TDIFvd/yCsJ+IH
vOYHXncDRSDs2yyGxQB5uYE4XlBTSqfENAHg5gcaID9uYZl1P4h/xucHl9Lc+cEPPZI6vcOW9EAE
P3a7XemYm3wAVcQ/tjXpcqwwi1Lmx+4/dShsoTBwYb7YoxFiqLvDPWqfg29m/xOj2ouOfhFhKyNq
R/Olso04hK2ztgw0CClLltfmEGPTGyTyt1uwKDkyIn4MA6JA8vgxauPHj10tP9ppKL9OgP34AwI8
Hrz+QetTUQ7QPdU/PTSgx2gW6pAFdI9S7QVfLBio4ZqSfGGJw+VmjTTrSMi0MW2aDHXbvUa3WbMZ
AdmGlM3SyJpR6qSJiU1/NMKYszOkszg+mKoH+DrdYYjp2pmttZclBADoh47bA6pM/UgHdffmRH/H
6+vjVhIlQCXlwPsgP1IdQVsrYOPVtXBfLw/vXewGGT650GUF5XuqebB0FRobjpjUpOOON325ap0r
U3ebZpyk2+B6Xx7XHwGRElTf1mXsdseZeP7y6bUepO6eghd0/2ouZh6Pw3u4o0Ide/dJVjXHXCf9
1TRX9M2G4TmBFgxxG+HfHOLJ1uSD+oduhP7BgbbqKqKuOVr1VyI43ScB5zLmOyd1xyeru08Be9Od
tEfPOc/nrXj+DhBuRZmRD4MRi1s6g15LqdttLP/a9JXjG+pM1txDRdkRZXnWbLSZ9HqS0S+N5LqG
0+mJppLhW0CyL5TostO+UOlW0OVWxOd8NYjvxsyLR8+rTDxXkXB9Ybszx5454+5KOKrgVdkkp3Rf
hn/KgbK+Uyd0qHK8W2aNsig8UWOHqq4C5WncN7NkvMyU/vGt+rSkOzfcjqDLuToxO0V5SQ1K0w45
dajeZNWz0pwuK2i4epksshUIHABalZF+XEhq6CeK4OkLN/0IA6DDU7pgoZ/Wt2telWTU24Rmb06h
Zr2a9vXoadeSouh9qr+v2DepVNK/piT/9OLZ86dvX0K7TVbNd3J4GzNQIQrq/enTiFwKQCanf+H/
mVKPQjMv2ukwnTrBvBg00YpeGtn61B7xP/OCdxyxfNzxeOLtiOw2YKF5PTrZGkMEqbuadKqorD34
5f8DUA/waw==
===END CRASH DUMP===

**Comment by DavyCraft648** [comment]
Your Customies version is outdated, you can download the latest one on [poggit](https://poggit.pmmp.io/ci/CustomiesDevs/Customies/Customies)

**Comment by TwistedAsylumMC** [comment]
Fixed in https://github.com/CustomiesDevs/Customies/commit/b6acc3eab6af3028dc5e3ec17a7204ba66e77a30
