### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LeonMazzoli** [CustomiesDevs/Customies#77]
[Thu_Jun_8-18.17.34-CEST_2023.log](https://github.com/CustomiesDevs/Customies/files/11690880/Thu_Jun_8-18.17.34-CEST_2023.log)
Please solved the problem

**Comment by royaljacques** [comment]
make static your function 
        CustomiesBlockFactory::getInstance()->registerBlock(static fn($id) => ();

**Comment by LeonMazzoli** [comment]
D'acc merci
