### ISSUE TITLE
Server crashes on latest verison

### ISSUE THREAD

**Issue by HotDogMastah** [CustomiesDevs/Customies#89]
"Too few arguments to function MochiBitsAndPieces\LazyCapt\MochiBitsAndPieces::MochiBitsAndPieces\LazyCapt\{closure}(), 0 passed in /home/container/plugins/Customies-master/src/block/CustomiesBlockFactory.php on line 83 and exactly 1 expected" (EXCEPTION) in "plugins/MochiBitsAndPieces/src/MochiBitsAndPieces/LazyCapt/MochiBitsAndPieces" at line 145

is the error being outputed by the server whilst line 145 is

`CustomiesBlockFactory::getInstance()->registerBlock(static fn(int $id) => new $class(new BlockIdentifier($id), $name, new BlockTypeInfo(new BlockBreakInfo(1))), "mochibitsandpieces:" . strtolower($name), $model, $creativeInfo);`

**Comment by unickorn** [comment]
Customies no longer accepts the callable fn(int $id), use a callable with no arguments instead and generate your own ID using BlockTypeIds::newId();

Your new code should look something like this:

...registerBlock(static fn() => new $class(new BlockIdentifier(BlockTypeIds::newId()), $name...
