### ISSUE TITLE
Speed issue on custom block

### ISSUE THREAD

**Issue by dadodasyra** [CustomiesDevs/Customies#93]
Weirdly when walking on custom block you get a speed pretty significant without any reason. Is there a missing tag ?

**Comment by dadodasyra** [comment]
What's the default value

**Comment by RtoxGaming** [comment]
0.4 if I'm not mistaken

**Comment by dadodasyra** [comment]
It doesn't change anything for me. I tried with even lower values, btw the default one is 0.6 in Block class

**Comment by RtoxGaming** [comment]
for my, is good, my code :

public function getFrictionFactor(): float {
        return 0.4;
}

**Comment by RtoxGaming** [comment]
but if for you this dosen't work, is very strange
